{{- if .Values.secrets.kibanaPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  kibana-password: {{ .Values.secrets.kibanaPassword | quote }}
{{- end }}

