# Default values for mecipe-instance-pre-a
# This is a YAML-formatted file.

global:
  dockerRegistry: ""
  imagePullSecrets: []

# Kafka Configuration
# Kafka Configuration
kafka:
  enabled: true
  image:
    registry: docker.io
    repository: confluentinc/cp-kafka
    tag: "7.5.0"
  persistence:
    enabled: true
    size: 10Gi
  listeners:
    client:
      protocol: PLAINTEXT
      servicePort: 9092
    internal:
      protocol: PLAINTEXT
      servicePort: 29092
  nodeId: 1
  processRoles: "broker,controller"
  controllerQuorumVoters: "1@kafka:29093"
  offsetsTopicReplicationFactor: 1
  transactionStateLogMinIsr: 1
  transactionStateLogReplicationFactor: 1

# KSQLDB Configuration
# KSQLDB는 dependency chart로 사용 불가하므로 직접 템플릿으로 구현
ksqldb:
  enabled: true
  image:
    repository: confluentinc/ksqldb-server
    tag: latest
  kafka:
    brokers: "kafka.instance-pre-a.svc.cluster.local:9092"
  streamsAutoOffsetReset: "earliest"
# Kafka UI Configuration
kafkaUI:
  enabled: true
  image:
    repository: provectuslabs/kafka-ui
    tag: latest
  kafkaClusters:
    - name: local
      bootstrapServers: "kafka.instance-pre-a.svc.cluster.local:9092"
  service:
    type: ClusterIP
    port: 8080

