{{- if or .Values.secrets.elasticsearchUsername .Values.secrets.elasticsearchPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.elasticsearchUsername }}
  elasticsearch-username: {{ .Values.secrets.elasticsearchUsername | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticsearchPassword }}
  elasticsearch-password: {{ .Values.secrets.elasticsearchPassword | quote }}
  {{- end }}
{{- end }}

