{{- if and .Values.enabled (or .Values.secrets.password .Values.auth.requirePass) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.password }}
  redis-password: {{ .Values.secrets.password | quote }}
  {{- else if .Values.auth.password }}
  redis-password: {{ .Values.auth.password | quote }}
  {{- end }}
{{- end }}


