# Default values for api-gateway
global:
  dockerRegistry: ""
  imagePullSecrets: []

name: api-gateway
namespace: app

nodeSelector:
  node-role: app

image:
  repository: "api-gateway"
  tag: "latest"
  pullPolicy: Always

replicaCount: 2

ingress:
  enabled: true
  host: ""
  tls:
    enabled: true
  tlsSecret: "mecipe-tls"
  annotationsSettings:
    certManager.enabled: true
    https.redirect.enabled: true
    securityHeaders.enabled: true

service:
  type: ClusterIP
  ports:
    http: 4000

env:
  nodeEnv: production
  port: "4000"
  placeApiServiceUrl: "http://place-api-service:4000"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 64Mi

# Secrets (should be set via --set or values file)
secrets:
  jwtSecret: ""

