{{- if or .Values.secrets.postgresPassword .Values.secrets.elasticPassword .Values.secrets.kibanaPassword .Values.secrets.databaseUser .Values.secrets.databasePassword .Values.secrets.databaseName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mecipe-instance-b.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-b.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.postgresPassword }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticPassword }}
  elastic-password: {{ .Values.secrets.elasticPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.kibanaPassword }}
  kibana-password: {{ .Values.secrets.kibanaPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseUser }}
  database-user: {{ .Values.secrets.databaseUser | quote }}
  {{- end }}
  {{- if .Values.secrets.databasePassword }}
  database-password: {{ .Values.secrets.databasePassword | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseName }}
  database-name: {{ .Values.secrets.databaseName | quote }}
  {{- end }}
{{- end }}

