{{- if .Values.certbot.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mecipe-instance-a.fullname" . }}-certbot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.certbot.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "mecipe-instance-a.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: certbot
        spec:
          restartPolicy: OnFailure
          containers:
          - name: certbot
            image: certbot/certbot:latest
            command:
            - certbot
            - renew
            - --quiet
            - --no-self-upgrade
            {{- if .Values.certbot.persistence.certbotConf.enabled }}
            volumeMounts:
            - name: certbot-conf
              mountPath: /etc/letsencrypt
            {{- end }}
            {{- if .Values.certbot.persistence.certbotWww.enabled }}
            - name: certbot-www
              mountPath: /var/www/certbot
            {{- end }}
          {{- if or .Values.certbot.persistence.certbotConf.enabled .Values.certbot.persistence.certbotWww.enabled }}
          volumes:
          {{- if .Values.certbot.persistence.certbotConf.enabled }}
          - name: certbot-conf
            persistentVolumeClaim:
              claimName: {{ include "mecipe-instance-a.fullname" . }}-certbot-conf-pvc
          {{- end }}
          {{- if .Values.certbot.persistence.certbotWww.enabled }}
          - name: certbot-www
            persistentVolumeClaim:
              claimName: {{ include "mecipe-instance-a.fullname" . }}-certbot-www-pvc
          {{- end }}
          {{- end }}
{{- end }}

