apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
    name: instance-a
    environment: {{ .Values.environment | default "production" }}

