{{- if .Values.mecipeWAS.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mecipe-instance-a.fullname" . }}-media-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mecipeWAS.persistence.storageClass }}
  storageClassName: {{ .Values.mecipeWAS.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mecipeWAS.persistence.size }}
{{- end }}
{{- if .Values.nginx.persistence.certbotConf.enabled }}
{{- if .Values.mecipeWAS.persistence.enabled }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mecipe-instance-a.fullname" . }}-certbot-conf-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nginx.persistence.certbotConf.size | default "1Gi" }}
{{- end }}
{{- if .Values.nginx.persistence.certbotWww.enabled }}
{{- if or .Values.mecipeWAS.persistence.enabled .Values.nginx.persistence.certbotConf.enabled }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mecipe-instance-a.fullname" . }}-certbot-www-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nginx.persistence.certbotWww.size | default "1Gi" }}
{{- end }}
{{- if .Values.nginx.persistence.media.enabled }}
{{- if or .Values.mecipeWAS.persistence.enabled .Values.nginx.persistence.certbotConf.enabled .Values.nginx.persistence.certbotWww.enabled }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mecipe-instance-a.fullname" . }}-media-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nginx.persistence.media.size }}
{{- end }}

