{{- if or .Values.secrets.databaseUrl .Values.secrets.jwtSecret .Values.secrets.secretLoginCrypto .Values.secrets.elasticsearchUsername .Values.secrets.elasticsearchPassword .Values.secrets.apiKey .Values.secrets.buildApiKey .Values.secrets.couponSecret .Values.secrets.productSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mecipe-instance-a.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecipe-instance-a.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.secretLoginCrypto }}
  secret-login-crypto: {{ .Values.secrets.secretLoginCrypto | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticsearchUsername }}
  elasticsearch-username: {{ .Values.secrets.elasticsearchUsername | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticsearchPassword }}
  elasticsearch-password: {{ .Values.secrets.elasticsearchPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.buildApiKey }}
  build-api-key: {{ .Values.secrets.buildApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.couponSecret }}
  coupon-secret: {{ .Values.secrets.couponSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.productSecret }}
  product-secret: {{ .Values.secrets.productSecret | quote }}
  {{- end }}
{{- end }}

