apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "common.nodeSelector" . }}
      containers:
      - name: ksqldb-server
        image: {{ include "common.image" (dict "Values" .Values "repository" .Values.image.repository "tag" .Values.image.tag) }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8088
          protocol: TCP
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.brokers | quote }}
        - name: KSQL_LISTENERS
          value: "http://0.0.0.0:8088"
        - name: KSQL_KSQL_SERVICE_ID
          value: "mecipe-ksqldb-service"
        - name: KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET
          value: {{ .Values.streamsAutoOffsetReset | quote }}
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10

