apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ksqldb.name" . }}-queries
  namespace: {{ include "ksqldb.namespace" . }}
data:
  queries.sql: |
{{ (.Files.Get "files/queries.sql") | indent 4 }}
