apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-connection.fullname" . }}-connection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-connection.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.connection.url }}
  DATABASE_URL: {{ .Values.connection.url | quote }}
  {{- else }}
  POSTGRES_HOST: {{ .Values.connection.host | quote }}
  POSTGRES_PORT: {{ .Values.connection.port | quote }}
  POSTGRES_USER: {{ .Values.connection.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.connection.password | quote }}
  POSTGRES_DB: {{ .Values.connection.database | quote }}
  DATABASE_URL: "postgresql://{{ .Values.connection.username }}:{{ .Values.connection.password }}@{{ .Values.connection.host }}:{{ .Values.connection.port }}/{{ .Values.connection.database }}?schema=public"
  {{- end }}

