apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.https }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}

