apiVersion: v2
name: mecipe-instance-a
description: Mecipe Instance A - Application and Streaming Services
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mecipe
  - kafka
  - nestjs
  - nginx
dependencies:
  - name: kafka
    version: "~22.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: ksqldb
    version: "~0.1.0"
    repository: "https://confluentinc.github.io/cp-helm-charts/"
    condition: ksqldb.enabled

