
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  loginId: 'loginId',
  loginPw: 'loginPw',
  username: 'username',
  loginType: 'loginType',
  userType: 'userType',
  nickname: 'nickname',
  email: 'email',
  isDisable: 'isDisable'
};

exports.Prisma.NoticeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  title: 'title',
  content: 'content',
  link: 'link',
  userId: 'userId'
};

exports.Prisma.BoardScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  title: 'title',
  content: 'content',
  link: 'link',
  startDay: 'startDay',
  endDay: 'endDay',
  isDisable: 'isDisable',
  isReplyAvaliable: 'isReplyAvaliable',
  userId: 'userId',
  boardType: 'boardType'
};

exports.Prisma.BoardImageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  thumbnailUrl: 'thumbnailUrl',
  width: 'width',
  height: 'height',
  size: 'size',
  isThumb: 'isThumb',
  isDisable: 'isDisable',
  boardId: 'boardId'
};

exports.Prisma.BoardReplyScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  content: 'content',
  isDisable: 'isDisable',
  userId: 'userId',
  boardId: 'boardId',
  boardReplyId: 'boardReplyId'
};

exports.Prisma.CafeBoardScalarFieldEnum = {
  boardId: 'boardId',
  cafeInfoId: 'cafeInfoId',
  createdAt: 'createdAt'
};

exports.Prisma.RegionCategoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  isDisable: 'isDisable',
  govermentType: 'govermentType'
};

exports.Prisma.ClosureRegionCategoryScalarFieldEnum = {
  ancestor: 'ancestor',
  descendant: 'descendant',
  depth: 'depth'
};

exports.Prisma.CafeInfoScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  isDisable: 'isDisable',
  name: 'name',
  code: 'code',
  regionCategoryId: 'regionCategoryId',
  address: 'address',
  directions: 'directions',
  businessNumber: 'businessNumber',
  ceoName: 'ceoName'
};

exports.Prisma.CafeThumbnailImageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  thumbnailUrl: 'thumbnailUrl',
  width: 'width',
  height: 'height',
  size: 'size',
  priority: 'priority',
  isDisable: 'isDisable',
  cafeInfoId: 'cafeInfoId'
};

exports.Prisma.CafeVirtualImageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  width: 'width',
  height: 'height',
  size: 'size',
  priority: 'priority',
  isDisable: 'isDisable',
  cafeInfoId: 'cafeInfoId'
};

exports.Prisma.CafeRealImageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  width: 'width',
  height: 'height',
  size: 'size',
  priority: 'priority',
  isDisable: 'isDisable',
  cafeInfoId: 'cafeInfoId'
};

exports.Prisma.CafeVirtualLinkScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  url: 'url',
  type: 'type',
  isDisable: 'isDisable',
  isAvaliable: 'isAvaliable',
  cafeInfoId: 'cafeInfoId'
};

exports.Prisma.CafeVirtualLinkThumbnailImageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  width: 'width',
  height: 'height',
  size: 'size',
  cafeVirtualLinkId: 'cafeVirtualLinkId'
};

exports.Prisma.CafeCouponGroupScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  code: 'code',
  name: 'name',
  tag: 'tag',
  description: 'description',
  isDisable: 'isDisable',
  startDay: 'startDay',
  endDay: 'endDay',
  issuanceStartDay: 'issuanceStartDay',
  issuanceEndDay: 'issuanceEndDay'
};

exports.Prisma.CafeCouponGoupPartnerScalarFieldEnum = {
  cafeCouponGroupId: 'cafeCouponGroupId',
  cafeInfoId: 'cafeInfoId'
};

exports.Prisma.ProxyUserScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  createdAt: 'createdAt',
  proxyUserType: 'proxyUserType',
  name: 'name',
  token: 'token',
  userId: 'userId'
};

exports.Prisma.CafeCouponScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  content: 'content',
  serialNumber: 'serialNumber',
  startDay: 'startDay',
  endDay: 'endDay',
  isDisable: 'isDisable',
  proxyUserId: 'proxyUserId',
  cafeCouponGroupId: 'cafeCouponGroupId'
};

exports.Prisma.CafeCouponHistoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  cafeCouponId: 'cafeCouponId',
  eventType: 'eventType',
  description: 'description',
  actorId: 'actorId',
  statusBefore: 'statusBefore',
  statusAfter: 'statusAfter'
};

exports.Prisma.CafeCouponQRCodeScalarFieldEnum = {
  serialNumber: 'serialNumber',
  createdAt: 'createdAt',
  isDisable: 'isDisable',
  cafeCouponId: 'cafeCouponId',
  size: 'size',
  base64Data: 'base64Data'
};

exports.Prisma.MetaViewerInfoScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  code: 'code',
  isDisable: 'isDisable',
  worldData: 'worldData',
  cafeInfoId: 'cafeInfoId'
};

exports.Prisma.MetaViewerMapScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  type: 'type',
  version: 'version',
  url: 'url',
  size: 'size',
  contentKey: 'contentKey',
  isDraco: 'isDraco',
  metaViewerInfoId: 'metaViewerInfoId'
};

exports.Prisma.MetaViewerActiveMapScalarFieldEnum = {
  id: 'id',
  updatedAt: 'updatedAt',
  metaViewerInfoId: 'metaViewerInfoId',
  activeRenderMapId: 'activeRenderMapId',
  activeColliderMapId: 'activeColliderMapId'
};

exports.Prisma.ProductCategoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  description: 'description',
  isDisable: 'isDisable',
  code: 'code'
};

exports.Prisma.ClosureProductCategoryScalarFieldEnum = {
  ancestor: 'ancestor',
  descendant: 'descendant',
  depth: 'depth'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  code: 'code',
  description: 'description',
  price: 'price',
  originalPrice: 'originalPrice',
  stockQuantity: 'stockQuantity',
  minOrderQuantity: 'minOrderQuantity',
  isDisable: 'isDisable',
  isAvailable: 'isAvailable',
  categoryId: 'categoryId',
  cafeInfoId: 'cafeInfoId',
  productRedirectUrl: 'productRedirectUrl',
  isSignature: 'isSignature'
};

exports.Prisma.WishlistProductScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  productId: 'productId',
  proxyUserId: 'proxyUserId'
};

exports.Prisma.ProductImageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  thumbnailUrl: 'thumbnailUrl',
  width: 'width',
  height: 'height',
  size: 'size',
  isDisable: 'isDisable',
  isThumb: 'isThumb',
  productId: 'productId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.LoginType = exports.$Enums.LoginType = {
  LOCAL: 'LOCAL',
  ADMIN: 'ADMIN',
  KAKAO: 'KAKAO',
  NAVER: 'NAVER',
  GOOGLE: 'GOOGLE',
  APPLE: 'APPLE',
  ZEPETO: 'ZEPETO'
};

exports.UserType = exports.$Enums.UserType = {
  GENERAL: 'GENERAL',
  BUSINESS: 'BUSINESS',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER'
};

exports.BoardType = exports.$Enums.BoardType = {
  BTALK: 'BTALK',
  BINFORM: 'BINFORM',
  BQUESTION: 'BQUESTION',
  BEVENT: 'BEVENT'
};

exports.GovermentType = exports.$Enums.GovermentType = {
  SPECIAL_CITY: 'SPECIAL_CITY',
  METROPOLITAN_CITY: 'METROPOLITAN_CITY',
  SPECIAL_SELF_GOVERNING_CITY: 'SPECIAL_SELF_GOVERNING_CITY',
  PROVINCE: 'PROVINCE',
  SPECIAL_SELF_GOVERNING_PROVINCE: 'SPECIAL_SELF_GOVERNING_PROVINCE',
  DISTRICT: 'DISTRICT',
  CITY: 'CITY',
  COUNTY: 'COUNTY',
  TOWN: 'TOWN',
  TOWNSHIP: 'TOWNSHIP',
  NEIGHBORHOOD: 'NEIGHBORHOOD',
  PLACENAME: 'PLACENAME'
};

exports.ProxyUserType = exports.$Enums.ProxyUserType = {
  ETC: 'ETC',
  WEB: 'WEB',
  ZEPETO: 'ZEPETO',
  WEV_VIEWER: 'WEV_VIEWER'
};

exports.CafeCouponEventType = exports.$Enums.CafeCouponEventType = {
  CREATED: 'CREATED',
  USED: 'USED',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
  UPDATE: 'UPDATE'
};

exports.CafeCouponStatus = exports.$Enums.CafeCouponStatus = {
  ACTIVE: 'ACTIVE',
  USED: 'USED',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED'
};

exports.MetaMapType = exports.$Enums.MetaMapType = {
  RENDER: 'RENDER',
  COLLIDER: 'COLLIDER'
};

exports.Prisma.ModelName = {
  User: 'User',
  Notice: 'Notice',
  Board: 'Board',
  BoardImage: 'BoardImage',
  BoardReply: 'BoardReply',
  CafeBoard: 'CafeBoard',
  RegionCategory: 'RegionCategory',
  ClosureRegionCategory: 'ClosureRegionCategory',
  CafeInfo: 'CafeInfo',
  CafeThumbnailImage: 'CafeThumbnailImage',
  CafeVirtualImage: 'CafeVirtualImage',
  CafeRealImage: 'CafeRealImage',
  CafeVirtualLink: 'CafeVirtualLink',
  CafeVirtualLinkThumbnailImage: 'CafeVirtualLinkThumbnailImage',
  CafeCouponGroup: 'CafeCouponGroup',
  CafeCouponGoupPartner: 'CafeCouponGoupPartner',
  ProxyUser: 'ProxyUser',
  CafeCoupon: 'CafeCoupon',
  CafeCouponHistory: 'CafeCouponHistory',
  CafeCouponQRCode: 'CafeCouponQRCode',
  MetaViewerInfo: 'MetaViewerInfo',
  MetaViewerMap: 'MetaViewerMap',
  MetaViewerActiveMap: 'MetaViewerActiveMap',
  ProductCategory: 'ProductCategory',
  ClosureProductCategory: 'ClosureProductCategory',
  Product: 'Product',
  WishlistProduct: 'WishlistProduct',
  ProductImage: 'ProductImage'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
