apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.hosts }}
  database-url: postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hosts }}/{{ .Values.postgres.database }}?schema=public
  {{- end }}
  {{- if and .Values.elasticsearch .Values.elasticsearch.hosts }}
  elasticsearch-hosts: {{ .Values.elasticsearch.hosts | quote }}
  {{- end }}
  {{- if and .Values.elasticsearch .Values.elasticsearch.username }}
  elasticsearch-username: {{ .Values.elasticsearch.username | quote }}
  {{- end }}
  {{- if and .Values.elasticsearch .Values.elasticsearch.password }}
  elasticsearch-password: {{ .Values.elasticsearch.password | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.secretLoginCrypto }}
  secret-login-crypto: {{ .Values.secrets.secretLoginCrypto | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.buildApiKey }}
  build-api-key: {{ .Values.secrets.buildApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.couponSecret }}
  coupon-secret: {{ .Values.secrets.couponSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.productSecret }}
  product-secret: {{ .Values.secrets.productSecret | quote }}
  {{- end }}

