{{- if .Values.secrets.superuser.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  ELASTIC_SUPERPASS: {{ .Values.secrets.superuser.password }}

  KIBANA_USER_NAME: {{ .Values.secrets.kibana.username }}
  KIBANA_USER_PASS: {{ .Values.secrets.kibana.password }}
  PRODUCER_USER_NAME: {{ .Values.secrets.producerUser.username }}
  PRODUCER_USER_PASS: {{ .Values.secrets.producerUser.password }}
  APP_USER_NAME: {{ .Values.secrets.appUser.username }}
  APP_USER_PASS: {{ .Values.secrets.appUser.password }}
{{- end }}
