apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  ELASTIC_SUPERUSER_PASSWORD: {{ .Values.secrets.password | default (randAlphaNum 32) | quote }}
  KIBANA_PASSWORD: {{ .Values.users.kibana.password | default (randAlphaNum 32) | quote }}
  PRODUCER_PASSWORD: {{ .Values.users.producer.password | default (randAlphaNum 32) | quote }}
  APP_PASSWORD: {{ .Values.users.app.password | default (randAlphaNum 32) | quote }}